---
title: "R Notebook"
output: html_notebook
---

# Load libraries
```{r}
library(tidyverse)
library(pals)
## library(ggtree)
library(ape)
library(adephylo)
library(Seurat)
library(SeuratObject)
library(ggplot2)
library(ggdendro)
library(cowplot)
library(phylogram)
library(dendextend)
library(circlize)
library(RColorBrewer)
library(viridis)
library(ggsci)
library(pvclust)
library(reshape2)
library(stats)
source("../utils/utilFxns.R")
source("../utils/plottingFxns.R")
```

# Full Object UMAP
## By cell class
```{r}
Human <- readRDS("../Species_Initial/Human_initial.rds")
pdf("../Figures/Human Supp Fig/UMAP_classes.pdf", w=6, h=6, useDingbats = FALSE)
DimPlot(Human, group.by = "cell_class", pt.size = .05, raster = TRUE) + theme(plot.title = element_blank())
dev.off()

```

## By sample
```{r}
pdf("../Figures/Human Supp Fig/UMAP_file.pdf", w=8, h=6, useDingbats = FALSE)
DimPlot(Human, group.by = "orig.file", pt.size = .05, raster = TRUE, shuffle = TRUE) + theme(plot.title = element_blank())
dev.off()
```

# RGC
## all RGC
```{r}
Human_RGC <- subset(Human, annotated_class == "RGC")

coords <- read.csv("../Species_Reference/UMAP_coor_all_RGCs.csv")
rownames(coords) <- coords$X
coords$X <- NULL

Human_RGC <- subset(Human_RGC, new_code %in% rownames(coords))


Human_RGC@reductions$umap@cell.embeddings <- as.matrix(coords[Human_RGC@meta.data$new_code, c("UMAP_1", "UMAP_2")])
rownames(Human_RGC@reductions$umap@cell.embeddings) <- rownames(Human_RGC@meta.data)


pdf("../Figures/Human Supp Fig/RGC_UMAP_type.pdf", w=8, h=6, useDingbats = FALSE)
DimPlot(Human_RGC, group.by = "annotated_type", pt.size = .1, raster = TRUE, label = TRUE) + theme(plot.title = element_blank()) + NoLegend()
dev.off()
```

## Exclude midgets
```{r}
Human_RGC <- subset(Human, annotated_class == "RGC")

coords <- read.csv("../Species_Reference/UMAP_coor_non_midget_RGCs.csv")
rownames(coords) <- coords$X
coords$X <- NULL

Human_RGC <- subset(Human_RGC, new_code %in% rownames(coords))


Human_RGC@reductions$umap@cell.embeddings <- as.matrix(coords[Human_RGC@meta.data$new_code, c("UMAP_1", "UMAP_2")])
rownames(Human_RGC@reductions$umap@cell.embeddings) <- rownames(Human_RGC@meta.data)


pdf("../Figures/Human Supp Fig/RGC_UMAP_type_nonMG.pdf", w=8, h=6, useDingbats = FALSE)
DimPlot(Human_RGC, group.by = "annotated_type", raster = TRUE, label = TRUE) + theme(plot.title = element_blank()) + NoLegend()
dev.off()
```

# BC
```{r}
Human_BC <- subset(Human, annotated_class %in% c("BC-OFF", "BC-ON"))
# only keep files with >500 cells to make integrated plot
Human_BC <- subset(Human_BC, orig.file %in% c("Hu082219_macular_All", "Hu218OSmAll", "Hu218OSPeriRetina", "Hu220235OSmAll", "Hu220OSPeriRetina", "Hu220OSPeriRetina"))
Human_BC <- ClusterSeurat(Human_BC, integrate.by = "orig.file")

pdf("../Figures/Human Supp Fig/BC_UMAP_type.pdf", w=8, h=6, useDingbats = FALSE)
DimPlot(Human_BC, group.by = "annotated_type", raster = TRUE, label = TRUE) + theme(plot.title = element_blank()) + NoLegend()
dev.off()
```

# Heatmap / Dotplot
```{r}
species <- "Human"
obj <- readRDS(paste0("../Species_Initial/", species, "_initial.rds"))

Idents(obj) <- "annotated_type"
obj@meta.data[WhichCells(obj, idents = "DB4_2"), "annotated_type"] <- "DB4"
obj@meta.data[WhichCells(obj, idents = "BBGB_2"), "annotated_type"] <- "BBGB"


obj@meta.data$plotting <- obj@meta.data$cell_class
Idents(obj) <- "annotated_class"

obj@meta.data[WhichCells(obj, idents = c("RGC", "BC-OFF", "BC-ON")), "plotting"] <- obj@meta.data[WhichCells(obj, idents = c("RGC", "BC-OFF", "BC-ON")), "annotated_type"]




# Build dendrograms for RGC and BC alone
obj_RGC <- subset(obj, annotated_class == "RGC")
Idents(obj_RGC) <- "annotated_type"
obj_RGC <- BuildClusterTree(obj_RGC, reorder = TRUE)
RGC_levels <- levels(Idents(obj_RGC))
RGC_p <- SuppFigure_dendro(obj_RGC)

obj_BC <- subset(obj, annotated_class %in% c("BC-OFF", "BC-ON"))
Idents(obj_BC) <- "annotated_type"
obj_BC <- BuildClusterTree(obj_BC, reorder = TRUE)
BC_levels <- levels(Idents(obj_BC))
BC_p <- SuppFigure_dendro(obj_BC)

# Set order for full object plotting
obj <- subset(obj, plotting %in% setdiff(unique(obj@meta.data$plotting), c("RGC", "BP", "Other")) )

obj@meta.data$plotting <- factor(obj@meta.data$plotting, levels = c(RGC_levels, BC_levels, "GabaAC", "GlyAC", "HC", "Rod", "Cone", "MG"))

# Generate DotPlot
RGC_markers= c("RBPMS2","RBPMS", "SLC17A6", "THY1")
BC_markers=c("VSX2", "OTX2", "GRM6", "VSX1", "CABP5", "GRIK1")
AC_markers=c("TFAP2A", "TFAP2B", "TFAP2C", "GAD1", "GAD2", "SLC6A9")
HC_markers=c("ONECUT1", "LHX1", "CALB1", "TPM3")
Cone_markers=c("PDE6H", "CRX", "ARR3")
Rod_markers=c("SAG", "PDC", "RHO")
MG_markers=c("SLC1A3","RLBP1", "APOE")

dp <- DotPlot(obj, features = c(RGC_markers, BC_markers, AC_markers, HC_markers, Rod_markers, Cone_markers, MG_markers), group.by = "plotting", assay = "RNA") + RotatedAxis() + NoLegend()


# Set dataframe for barplots
class_df <- data.frame(table(obj@meta.data$plotting))
rownames(class_df) <- class_df$Var1

# Generate Heatmap
hmap <- SuppFigure_hmap(obj, scale = FALSE)

# Set parameters for plotting
spacing = 850.46 / 936 / length(c(RGC_levels, BC_levels, "GabaAC", "GlyAC", "HC", "Rod", "Cone", "MG"))
bar_axis = .026
top_gap = 4/936
bottom_gap = 1 - 857 / 936
dendro_gap = 30 / 936

# All plots
pdf(paste0("../Figures/Human Supp Fig/", species, ".pdf"), w=11, h=13, useDingbats = FALSE)
ggdraw() +
  draw_plot(dp, x=.05, y=0, width = .7, height = 1) +
  draw_plot(ClassBarPlot(class_df, RGC_levels, "gold"), x=0.73, y=0.065, width = .1, height = bar_axis + length(RGC_levels)*spacing) +
  draw_plot(ClassBarPlot(class_df, BC_levels, "burlywood3"), x=.73, y=.065+length(RGC_levels)*spacing, width = .1, height = bar_axis+length(BC_levels)*spacing) +
  draw_plot(ClassBarPlot(class_df, c("GabaAC", "GlyAC"), "sienna1"), x=.73, y= 1-top_gap-6*spacing-bar_axis, width = .1, height = bar_axis+2*spacing) +
  draw_plot(hmap, x = .83, y = 0, width = .17, height = 1) +
  draw_plot(RGC_p, x=0, y= bottom_gap - dendro_gap, width = .08, height = length(RGC_levels)*spacing + 2*dendro_gap) + 
  draw_plot(BC_p, x=0, y=bottom_gap + length(RGC_levels)*spacing - dendro_gap, width = .08, height = length(BC_levels)*spacing + 2*dendro_gap) 
dev.off()

```